apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp-1
  template:
    metadata:
      labels:
        app: flaskapp-1
    spec:
      containers:
      - name: flask-app
        image: irehankhan/display-pod-name:1.0
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: FLASK_ENV
          value: development
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Get the pod name from metadata

---
apiVersion: v1
kind: Service

metadata:
  name: flaskapp-service-1

spec:
  selector:
    app: flaskapp-1

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort